# Site settings
title: KJG Dortmund-Wickede
email: kjgdortmundwickede@gmail.com
url: http://www.kjg-dortmund-wickede.de/
description: "Write an awesome description for your new site here.
              You can edit this line in _config.yml.
              It will appear in your document head meta (for Google
              search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Gemeinde - Jugendarbeit - Glauben"
meta_author: Henning Moldenhauer

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2
# content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 00b6be
 # primary-rgb: "122,144,120" "51,197,203"
 # Hovering Color
  primary-rgb: "199,105,78"
  secondary: 006d84 #006d84
  secondary-dark: 01446b #01446b


# Footer settings
footer:
  copyright: KJG Dortmund-Wickede
  location: Anschrift
  social: Im Netz
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble,
# pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://de-de.facebook.com/KJG-Dortmund-Wickede-535434733211557/
  - title: github
    url: https://github.com/kjg-dortmund-wickede

# Postal address (add as many lines as necessary)
address:
  - line: Wickeder Hellweg 59
  - line: 44319 Dortmund

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme
          created by <a target="_blank" href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
