# Site settings
title: YALP
email: your-email@domain.com
url: https://github.com/secur3gamer/yalp
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "Security Analyst, Ocassional Web Developer"
meta_author: LastName FirstName

landing:
  - title: Blog
    url: https://firstexample.com
  - title: Resume
    url: https://secondexample.com
  - title: Third Link
    url: https://thirdexample.com
  - title: Fourth Link
    url: https://fourthexample.com
  - title: Fifth Link
    url: https://fifthexample.com

aboutblurb:
  - content: This is a fork of the Freelancer Jekyll theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional LESS stylesheets for easy customization.
  - content: Because this is simply a landing page, posts have been removed. The portfolio grid was also removed.
  - content: More content customisation is now possible in _config.yml, including the button links (landing) and the 'about' section.

aboutbtn:
  - title: Download Theme
    url: https://github.com/secur3gamer/yalp

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 333333 #333333
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 429077 #429077
  secondary-dark: 2c3e50 #2c3e50

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'YALP is a free to use, open source Bootstrap theme forked by <a href="https://github.com/secur3gamer/yalp" target="_blank">me</a>, originally created by <a href="http://startbootstrap.com" target="_blank">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
