---
title: Mike P. Sinn
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mike@quantimo.do
url: https://mike.quantimo.do
description: Web Development - Data Science - Mobile Development
skills: Web Development - Data Science - Mobile Development
meta_author: Sinn Mike
keywords: quantimodo, think by numbers, web development, business intelligence
google_verify: 
bing_verify: 
contact: static
disqus_shortname: mikepsinn
color:
  primary: 18bc9c
  primary-rgb: '24,288,156'
  secondary: 2c3e50
  secondary-dark: 233140
footer:
  copyright: Mike P. Sinn
  location: Location
  social: Around the Web
  credits: Credits
social:
- title: twitter
  url: http://twitter.com/thinkbynumbers
- title: facebook
  url: https://www.facebook.com/mikepsinn
- title: stack-overflow
  url: http://stackoverflow.com/users/3785491/mikepsinn
- title: bitbucket
  url: http://bitbucket.org/mikepsinn
- title: github
  url: http://github.com/mikepsinn
address:
- line: 167 Glenwood Dr.
- line: Glen Carbon, IL 62034
credits: <a href="https://www.flaticon.com/"title="Flaticon">www.flaticon.com</a>
  <br> <a href="http://startbootstrap.com">Start Bootstrap</a>
markdown: kramdown
permalink: pretty
exclude:
- Gemfile.lock
- node_modules
- ".idea"
